---
abstract: 'IRC plugin to fetch Vim tips'
author:
  - 'Curtis Brandt, C<< <curtis at cpan.org> >>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-WWW-Vim-Tips
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  HTML::TreeBuilder::XPath: 0
  LWP::Simple: 0
  POE::Component::IRC::Plugin: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/aggrolite/POE-Component-IRC-Plugin-WWW-Vim-Tips/issues
  homepage: https://github.com/aggrolite/POE-Component-IRC-Plugin-WWW-Vim-Tips
  repository: https://github.com/aggrolite/POE-Component-IRC-Plugin-WWW-Vim-Tips.git
version: 0.14
x_contributors:
  - 'Curtis Brandt <curtisjbrandt@gmail.com>'
